language: python
sudo: false
python:
  - "3.6"
  - "2.7"
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "2.7"
      env: TOXENV=py27

install: pip install tox
script: tox
cache: pip
